### ISSUE TITLE
Development browser

### ISSUE THREAD

**Issue by cooperl09** [Planteome/plant-trait-ontology#1]
Now that we will be working from here, we will need to link the TO dev browser to it, so that the changes get uploaded.

http://palea.cgrb.oregonstate.edu/amigo/TO_dev

**Comment by elserj** [comment]
Just to make sure what you mean, you want the TO browser to be updated from one on here instead of svn nightly?  Or is there some kind of dbxref or mapping?

**Comment by cooperl09** [comment]
Yes, the TO browser should be updated from the OBO on here instead of svn nightly.

**Comment by cmungall** [comment]
I was assuming that there would be two browsers: planteome-dev and planteome

Is there a reason for having specific browsers for specific ontologies?

**Comment by elserj** [comment]
The browser she is talking about is a separate AmiGO 1.8 instance that is just used for TO development.  It isn't part of planteome exactly, but since the trait OBO file is now hosted here on github, she wants me to have it set to automatically grab the one from here as this is the version that will be current.  I assume once we get everything up, the use of the separate browser will be subsumed at some point.

**Comment by cmungall** [comment]
got it

**Comment by elserj** [comment]
Done.  Git doesn't have a mechanism for downloading a single file like svn did, but since we are on github, a simple wget will work in its place.  The command I used is:
wget https://github.com/Planteome/plant-trait-ontology/raw/master/plant-trait-ontology.obo

I also had to modify the loading script to account for the filename change.

**Comment by cooperl09** [comment]
Thanks Justin!
