### ISSUE TITLE
change definition of TO:0000084 root number

### ISSUE THREAD

**Issue by leova** [Planteome/plant-trait-ontology#357]
`Average sum of number of roots in a plant derived per experiment.` is the description of a variable, not a trait

http://planteome.org/amigo/cgi-bin/crop_amigo/term_details?term=TO:0000084

**Comment by austinmeier** [comment]
Proposed def'n: a root anatomy and morphology trait (TO:0000043) which is the number of roots (PO:0009005) in a whole plant (PO:0000003).

**Comment by cooperl09** [comment]
This term should actually be moved to be a child of root system morphology trait (need to create), not root morphology trait.  It does not make sense to say that the number of roots in a plant is a root morphology trait.  Also, please use the current term names, rather than the outdated ones. 

Proposed def'n:
root number (TO:0000084):  A root system morphology trait (TO: need to create) which is the number of roots (PO:0009005) in a root system (PO:ID) of a  whole plant (PO:0000003).

**Comment by ejohnson1** [comment]
Changed relationship from SubClass of root morphology trait (TO:0000043) to SubClass of root system morphology trait (TO:0000985).
Revised term root number (TO:0000084): A root system morphology trait (TO:0000985) which is the number of roots (PO:0009005) in a root system (PO:0025025) of a whole plant (PO:0000003).
added dbxref to PO and PATO:0001555

**Comment by maxglycine** [comment]
Again, to get my head around the rational.  I note that instead of putting the PATO accession in the definition, you instead added it as a dbxref.  Why?

How does that impact the reasoning (reasoner)?  Does it use that at all or is this mainly for humans?


On Nov 18, 2015, at 6:47 PM, ejohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Changed relationship from SubClass of root morphology trait (TO:0000043) to SubClass of root system morphology trait (TO:0000985).
Revised term root number (TO:0000084): A root system morphology trait (TO:0000985) which is the number of roots (PO:0009005) in a root system (PO:0025025) of a whole plant (PO:0000003).
added dbxref to PO and PATO:0001555

—
Reply to this email directly or view it on GitHub<https://github.com/Planteome/plant-trait-ontology/issues/357#issuecomment-157911260>.

Rex Nelson
Computational Biologist
G329 Agronomy Hall
Iowa State University
Ames, IA 50011
nelsonrt@iastate.edu<mailto:nelsonrt@iastate.edu>
515-294-1297

"Time flies like an arrow. Fruit flies like a banana"

**Comment by cmungall** [comment]
A reasoner uses neither the textual definition nor the dbxref. We model 
these as "annotation assertion axioms" as distinct from "logical 
axioms". A reasoner only uses logical axioms.

Fields like dbxrefs can be used computationally (e.g. in a query) but 
they would have to be translated to a logical axiom to be visible to a 
reasoner (for example, you could write a script to translate all xrefs 
to equivalentClasses axioms)

**Comment by austinmeier** [comment]
*caution: wild speculation incoming*

I believe that everything in the annotation fields are [string] based, and are not used by the reasoner at all.  The reasoner seems to focus on the axioms.  This question would be better answered by someone with more than 7 days experience in Protege.

**Comment by cmungall** [comment]
You are 100% correct.

More precisely, in OWL terminology: the reasoner only uses *logical* 
axioms. In OWL, somewhat intuitively, annotations are also "axioms", but 
they are "non-logical" or synonymously "annotation axioms". Being 
non-logical, they are not inspected by a logic-based reasoner.

**Comment by cooperl09** [comment]
root number (TO:0000084): 
revised def'n: 
was: A root system morphology trait (TO:0000985) which is the number of roots (PO:0009005) in a root system (PO:0025025) of a whole plant (PO:0000003).

revised: A root system morphology trait (TO:0000985) which is the number of roots (PO:0009005) in a root system (PO:0025025).

EA: 'has number of'
 and ('inheres in' some 'root') and ('occurs in' some 'root system')

Removed is_a relationship to abiotic stress
______________________________________
