### ISSUE TITLE
Remove IDs from textual definitions

### ISSUE THREAD

**Issue by cmungall** [Planteome/plant-trait-ontology#360]
We no longer need these, as the external classes are explicit in the OWL edition of TO. 

I propose the following:

 1. Embedded IDs in text definitions are used to validate and fill out OWL definitions (me)
 2. Then, All embedded IDs are removed provided an OWL definition is in place
 3. Repeat until all gone

**Comment by maxglycine** [comment]
Chris:

I am confused.  I thought since Thursday of last week the “official” ontology was in OWL.  That would mean that any further development would be on the TO.owl file using Protege.  But it seems that Austin is using OBOEdit on an OBO file.  Which version (OWL or OBOB) should we be working on?





On Nov 19, 2015, at 12:49 PM, Chris Mungall <notifications@github.com<mailto:notifications@github.com>> wrote:


We no longer need these, as the external classes are explicit in the OWL edition of TO.

I propose the following:

  1.  Embedded IDs in text definitions are used to validate and fill out OWL definitions (me)
  2.  Then, All embedded IDs are removed provided an OWL definition is in place
  3.  Repeat until all gone

—
Reply to this email directly or view it on GitHub<https://github.com/Planteome/plant-trait-ontology/issues/360>.

Rex Nelson
Computational Biologist
G329 Agronomy Hall
Iowa State University
Ames, IA 50011
nelsonrt@iastate.edu<mailto:nelsonrt@iastate.edu>
515-294-1297

"Time flies like an arrow. Fruit flies like a banana"

**Comment by cooperl09** [comment]
There were several reasons they were added in the first place.  Firstly, it forces the curators who are writing the definitions to be precise and use the defined terms from the existing ontologies, and it alerts users that these are related terms.  Secondly, in the browser these can be set as hyperlinks so the user can navigate easily to the related terms.  In many cases they will not be part of OWL equivalence axioms, but are useful to the users.   

What makes sense to the computer scientists will not always make sense to the users of the ontology.

**Comment by cmungall** [comment]
@maxglycine -- see https://github.com/Planteome/plant-trait-ontology#ontology-editors-guide

> Ontology editors should edit plant-trait-ontology.obo using Protege5 beta18 or higher.

@austinmeier should not be editing this in Protege (maybe your thinking of the stress ontology)

Regarding official editions of the ontology. As far as consumers of the ontology are concerned, there are two products, to.obo and to.owl. Neither is more official than the other.

**Comment by cmungall** [comment]
@cooperl09 let's spec out the requirements of what users require. Of course, I am concerned about actual users of the ontology, I don't care about computer scientists.
