### ISSUE TITLE
Tomato spotted wilt virus resistance

### ISSUE THREAD

**Issue by sammyjava** [Planteome/plant-trait-ontology#467]
I'd like to add **Tomato spotted wilt virus resistance** as a child of TO:0000148, viral disease resistance. This is an important trait in cultivated peanut, e.g. as studied by Agarwal, G. et al. _High-density genetic map using whole-genome resequencing for fine mapping and candidate gene discovery for disease resistance in peanut._ Plant Biotechnol. J. 16, 1954–1967 (2018).

Thanks!

**Comment by cooperl09** [comment]
Term has been created:
[Term]
id: TO:0001156
name: tomato spotted wilt virus response
def: "A viral disease response trait (TO:0000148) caused by tomato spotted wilt virus." [DOI:10.1111/pbi.12930, NCBITaxon:3052585, TO:cooperl]
synonym: "TSWV (exact)" EXACT []
xref: TO_GIT:467
is_a: TO:0000148 ! viral disease response trait
