### ISSUE TITLE
Late leaf spot resistance

### ISSUE THREAD

**Issue by sammyjava** [Planteome/plant-trait-ontology#468]
I'd like to add **Late leaf spot resistance** as a child of TO:0000439, fungal disease resistance. Late leaf spot resistance is important in cultivated peanut, and is described as such:

Traits bearing on the reaction of the plant or plant part to Phaeoisariopsis personata infection and/or traits that affect the biology of the fungus in the presence of the plant.  Phaeoisariopsis personata causes late leaf spot in peanut; it has also been named Cercosporidium personatum and Mycosphaerella berkeleyi.

See e.g. Agarwal, G. et al. _High-density genetic map using whole-genome resequencing for fine mapping and candidate gene discovery for disease resistance in peanut_, Plant Biotechnol. J. 16, 1954–1967 (2018)

**Comment by cooperl09** [comment]
Requested term has been created:
id: TO:0001155
name: peanut late leaf spot disease response
def: "An Ascomycete fungal disease response trait (TO:0001145) caused by Nothopassalora personata." [DOI:10.1111/pbi.12930, NCBITaxon:2060155, TO:cooperl]
synonym: "LLS (exact)" EXACT []
xref: TO_GIT:468
is_a: TO:0001145 ! Ascomycete fungal disease response
