### ISSUE TITLE
Early leaf spot resistance

### ISSUE THREAD

**Issue by sammyjava** [Planteome/plant-trait-ontology#469]
I'd like to add **Early leaf spot resistance** as a child of TO:0000439, fungal disease resistance. It is important in cultivated peanut and is described as:

Traits bearing on the reaction of the plant or plant part to Cercospora arachidicola infection and/or traits that affect the biology of the fungus in the presence of the plant.  Cercospora arachidicola causes the foliar disease Early leaf spot in peanut.  Synonyms for the anamorph (asexual reproductive stage) include Passalora arachidicola and Cercospora arachidis var. macrospora.  The teleomorph (sexual reproductive stage) is known as Mycosphaerella arachidis.

See e.g. Agarwal, G. et al. _High-density genetic map using whole-genome resequencing for fine mapping and candidate gene discovery for disease resistance in peanut._ Plant Biotechnol. J. 16, 1954–1967 (2018)

**Comment by cooperl09** [comment]
I suggest you annotate the data with the existing term from our partners at the Crop Ontology:

Early leaf spot severity CO_337:0000239
Def'n: Early leaf spot disease severity caused by agent Cercospora arachidicola.

While we have not yet incorporated the Groundnut Ontology into Planteome, we anticipate doing so in the near future. 
https://github.com/Planteome/CO_337-groundnut-traits

This term would be mapped to the existing TO term:  TO:0002702  Cercospora leaf spot resistance, which is the general class for the diseases caused by various species in the genus Cercospora.
