### ISSUE TITLE
Clean up GitHub issues references in xrefs

### ISSUE THREAD

**Issue by cthoyt** [Planteome/plant-trait-ontology#482]
Currently, there are three prefixes introduced throughout TO `TO_GIT` (430 occurrences), `GIT_TO` (3 occurrences), and `OBO_S2F_TO` (1 occurrence). All of these seem to correspond to GitHub issues. I think there are two steps that would be good for normalizing these:

1. Replace these prefixes with full URLs like https://github.com/Planteome/plant-trait-ontology/issues/. For example, 
2. Switch these from xrefs to `rdf:seeAlso` relationships

I will send a PR to demonstrate. For example,

```
xref: TO_GIT:54
```
becomes

```
property_value: seeAlso https://github.com/Planteome/plant-trait-ontology/issues/54
```

**Comment by cooperl09** [comment]
I have cleaned up the TO_GIT xrefs (and corrected the 3 that were entered incorrectly). There are 455 xrefs to the GitHub issue trackers. I removed the old xrefs to the SF tracker since that information has been transferred to the GitHub Issue trackers now.  I tested the suggested change from the  TO_GIT xref to the property_value: seeAlso https://github.com/Planteome/plant-trait-ontology/issues/54.  The URL does not show up on our AmiGO browser, so it does not create a link to the associated issue. 
You can see this here: https://dev.planteome.org/amigo/term/TO:0000017
The existing xrefs work fine and allow users and curators easy access to the associated history of the terms.
