### ISSUE TITLE
plant morphology trait (TO:0000017)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#54]
current def'n: This category belongs to traits associated with changes in the anatomy or structure of the plant at organ, tissue or cellular level. 

Propose revised def'n:
A plant trait [(TO:0000387](http://purl.obolibrary.org/obo/%28TO_0000387)) which is associated with the anatomy or morphology of a plant anatomical entity [(PO:0000003](http://purl.obolibrary.org/obo/%28PO_0000003)) or one or more constituent cellular components [(GO:0005575](http://purl.obolibrary.org/obo/%28GO_0005575)) contained therein. 

Reported by: cooperl09

Original Ticket: [obo/plant-trait-ontology-to-requests/53](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/53)

**Comment by ejohnson1** [comment]
revised term morphology trait (TO:0000017) and def'n: A plant trait (TO:0000387) which is a morphological quality of a plant anatomical entity (PO:0025131) or one or more constituent cellular components (GO:0005575) contained therein.
added xref (TO_GIT:54) to morphology trait (TO:0000017)

**Comment by phismith** [comment]
This looks wrong.

a) need 'of' before 'one or more'
b) we do not want to allow qualities of pluralities of cellular components;
only single entities can have qualities
c) cellular components in GO's terms are parts of cells; the definition
would imply that a morphology trait could be either a quality of plant
structures (always bigger than cells) or of entities at the level of
cellular components (always small than cells) but not of cells taken singly

BS

**Comment by cooperl09** [comment]
Revised name and def'n:
was: morphology trait (TO:0000017) and def'n: A plant trait (TO:0000387) which is a morphological quality of a plant anatomical entity(PO:0025131) or one or more constituent cellular components (GO:0005575) contained therein.

Revised: 
plant morphology trait (TO:0000017):  A plant trait (TO:0000387) which is a morphological quality of a plant anatomical entity (PO:0025131) or a constituent cellular component (GO:0005575) contained therein.
This definition includes plant cell.  
plant cell (PO:0009002):  A cell which is a plant structure (PO:0009011). [source: GO:0005623, POC:curators]
This has been part of the PO since the early days.   There are about 40 plant cells in the PO.
